// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System.Text.Json;
using AgentControlSpec;
using AgentControlSpec.ContentSafety;

/// <summary>
/// Drives the adapter from real request streams.
///
/// The earlier tests construct sessions directly, which proves the accounting
/// but says nothing about whether this package's model of a payload matches the
/// contract a front door actually receives. The fixture here was generated by
/// compiling the service's own proto and building genuine messages, then
/// rendering them as canonical protobuf JSON so this test needs no protobuf
/// dependency. Field names, enum names, and the oneof structure are the wire
/// ones.
///
/// The property under test is that translating each message the obvious way and
/// feeding it to a session reproduces the offsets the front door itself would
/// compute, including its rule that only a literal user request advances the
/// prompt track.
/// </summary>
internal static class ContentSafetyMessageStreams
{
    private static void Assert(bool condition, string message)
    {
        if (!condition)
        {
            throw new InvalidOperationException($"ContentSafetyMessageStreams: {message}");
        }
    }

    private static string LocateFixture()
    {
        var directory = AppContext.BaseDirectory;
        for (var i = 0; i < 10 && directory is not null; i++)
        {
            var candidate = Path.Combine(
                directory, "tests", "conformance", "streaming", "content-safety", "content-safety-message-streams.json");
            if (File.Exists(candidate))
            {
                return candidate;
            }

            directory = Path.GetDirectoryName(directory);
        }

        throw new FileNotFoundException("content-safety-message-streams.json not found");
    }

    /// <summary>Translate a wire source name into this package's copy.</summary>
    private static ContentSafetySource Translate(string wireName) => wireName switch
    {
        "UNKNOWN" => ContentSafetySource.Unknown,
        "USER_REQUEST" => ContentSafetySource.UserRequest,
        "MODEL_GENERATED" => ContentSafetySource.ModelGenerated,
        "CONCAT_ALL" => ContentSafetySource.ConcatAll,
        "CONTEXT" => ContentSafetySource.Context,
        "PRE_TOOL_CALL" => ContentSafetySource.PreToolCall,
        "POST_TOOL_CALL" => ContentSafetySource.PostToolCall,
        "PRE_RUN" => ContentSafetySource.PreRun,
        "POST_RUN" => ContentSafetySource.PostRun,
        _ => throw new InvalidOperationException($"unknown wire source {wireName}"),
    };

    public static Task RunAsync()
    {
        using var document = JsonDocument.Parse(File.ReadAllText(LocateFixture()));
        var streams = document.RootElement.GetProperty("streams");
        var cases = 0;
        var payloads = 0;

        foreach (var stream in streams.EnumerateArray())
        {
            var caseId = stream.GetProperty("case").GetInt32();
            var start = stream.GetProperty("start_rune_offset").GetInt32();
            var expectedPrompt = stream.GetProperty("expected_prompt_end").GetInt32();
            var expectedCompletion = stream.GetProperty("expected_completion_end").GetInt32();

            ContentSafetySession? session = null;
            var sawConfig = false;

            foreach (var message in stream.GetProperty("messages").EnumerateArray())
            {
                if (message.TryGetProperty("config", out var config))
                {
                    // Configuration precedes every payload, which is what the
                    // contract requires and what the session assumes.
                    Assert(!sawConfig, $"case {caseId}: a second configuration message arrived");
                    sawConfig = true;

                    var offset = config.TryGetProperty("start_rune_offset", out var o)
                        ? o.GetInt32()
                        : 0;
                    Assert(offset == start, $"case {caseId}: configuration offset disagreed");

                    session = ContentSafetySession.Create(new ContentSafetySessionOptions
                    {
                        RequestStartOffset = offset,
                        ResponseStartOffset = offset,
                        Tasks = new[]
                        {
                            new ContentSafetyTask
                            {
                                Label = "harm",
                                Action = ContentSafetyAction.Block,
                                Criterion = new BlockingCriterion
                                {
                                    Enabled = true,
                                    Kind = BlockingCriterionKind.Severity,
                                    AllowedSeverity = 4,
                                },
                                AppliesTo = new[] { ContentSafetyAppliedSource.All },
                            },
                        },
                    });
                    continue;
                }

                if (!message.TryGetProperty("payload", out var payload))
                {
                    continue;
                }

                Assert(session is not null, $"case {caseId}: a payload arrived before configuration");

                // A proto3 field at its default is omitted from canonical JSON,
                // so an absent source is UNKNOWN and an absent text is empty.
                var wireSource = payload.TryGetProperty("source_type", out var s)
                    ? s.GetString()!
                    : "UNKNOWN";
                var text = payload.TryGetProperty("incremental_text", out var t)
                    ? t.GetString()!
                    : string.Empty;

                session!.OnPayload(Translate(wireSource), ContentSafetyTextKind.Unspecified, text);
                payloads++;
            }

            Assert(session is not null, $"case {caseId}: no configuration message");
            Assert(
                session!.ReceivedOffset(StreamTrack.Request) == expectedPrompt,
                $"case {caseId}: prompt track ended at "
                + $"{session.ReceivedOffset(StreamTrack.Request)}, the front door says {expectedPrompt}");
            Assert(
                session.ReceivedOffset(StreamTrack.Response) == expectedCompletion,
                $"case {caseId}: completion track ended at "
                + $"{session.ReceivedOffset(StreamTrack.Response)}, "
                + $"the front door says {expectedCompletion}");
            cases++;
        }

        Assert(cases > 0, "no streams were replayed");
        Console.WriteLine(
            $"AgentControlSpec content safety message streams passed "
            + $"({cases} streams, {payloads} payloads).");
        return Task.CompletedTask;
    }
}
