/* auto-generated by NAPI-RS */
/* eslint-disable */

export declare class ExternalObject<T> {
  readonly '': {
    readonly '': unique symbol
    [K: symbol]: T
  }
}
/**
 * Evaluate one agent context (JSON object per AGENT-HOOKS-0.1 §4) and
 * return the verdict as wire JSON.
 */
export declare function intercept(handle: ExternalObject<Handle>, contextJson: string): string

/**
 * Build a runtime handle from a manifest path using the zero-config
 * dispatchers (bundled annotators; Rego in process, Cedar through the
 * built-in evaluator, `test` policies through their embedded verdict).
 */
export declare function interceptorNew(manifestPath: string): ExternalObject<Handle>

/**
 * Activate the manifest at `manifest_path`, readying every policy it
 * binds, against the zero-config dispatchers.
 *
 * This is the expensive call: it reads the manifest, loads every Rego
 * module and data document, and compiles the entrypoint each
 * intervention point queries. Do it once per policy version and keep
 * the handle; `policyEvaluate` then costs no I/O and no compile.
 *
 * Readying is bounded by the eval timeout. A policy too slow to ready
 * inside it activates anyway and pays that cost on its first
 * evaluation instead.
 */
export declare function policyActivate(manifestPath: string): ExternalObject<PolicyHandle>

/**
 * Activate a manifest and its Rego, both supplied as values rather
 * than read from disk.
 *
 * `manifest_yaml` is the manifest text. `bundles_json` is a JSON
 * object mapping a policy id declared in that manifest to
 * `{"modules": {name: source}, "data": [{"mount": [..], "document":
 * {..}}]}`, replacing whatever `bundle` path the manifest names. A
 * service holding manifests and Rego in a database activates from them
 * directly rather than staging a temporary directory per activation.
 *
 * Throws when the manifest does not parse, when a key of `bundles_json`
 * names a policy the manifest does not declare as Rego, and when a Rego
 * policy is left naming a relative `bundle` or data path: that path would
 * resolve against the process working directory, since a manifest
 * parsed from a string has no directory of its own. An absolute path is
 * left as written.
 */
export declare function policyActivateFromMemory(manifestYaml: string, bundlesJson: string): ExternalObject<PolicyHandle>

/**
 * Evaluate one intervention point against an activated policy and
 * return the verdict as wire JSON.
 *
 * `point` is an agent-hooks intervention point name, such as `input`
 * or `pre_tool_call`. `context_json` is the agent context object
 * (AGENT-HOOKS-0.1 §4).
 *
 * A policy that does not bind `point` is not thrown at: it fails
 * closed with a `runtime_error:*` deny, exactly as every other
 * evaluation failure does. An unknown point name is a boundary problem
 * and throws.
 */
export declare function policyEvaluate(handle: ExternalObject<PolicyHandle>, point: string, contextJson: string): string

/**
 * The intervention points this policy version binds, in manifest
 * order, as agent-hooks wire names.
 */
export declare function policyInterventionPoints(handle: ExternalObject<PolicyHandle>): Array<string>

/**
 * Recompute `track`'s watermark. Returns the new offset when the
 * watermark advanced, `null` when it did not or the session has ended
 * (matching the Rust `Option<u32>`).
 */
export declare function streamSessionAdvance(handle: ExternalObject<StreamHandle>, track: string): number | null

/** Declare that no further payload will arrive. Idempotent. */
export declare function streamSessionEndOfPayloads(handle: ExternalObject<StreamHandle>): void

/**
 * Settle the session and return the completion as JSON, carrying
 * `reason`, `transformed` and `is_clean`. Settling twice returns the
 * same completion.
 */
export declare function streamSessionFinish(handle: ExternalObject<StreamHandle>): string

/**
 * Open a session from a config JSON object.
 *
 * Matches `acs_stream_session_new`: takes `safety_level` (`blocking`,
 * `complete` or `deferred`), the per-track start offsets
 * `request_start_rune_offset` and `response_start_rune_offset`, and
 * the task name arrays `request_tasks` and `response_tasks`. An empty
 * task array means that track is unmediated; payload on it fails
 * closed. A configuration mediating neither track is refused.
 *
 * The wrapper takes a JSON string rather than a napi object so the
 * config surface is identical to the other language SDKs and offset
 * coercion happens in one place.
 */
export declare function streamSessionNew(configJson: string): ExternalObject<StreamHandle>

/**
 * Report that `runes` more runes of `source_type` arrived and return
 * the track's new end offset. Boundary failures throw; a streaming
 * accounting failure throws with the engine's message and puts the
 * session into its terminal state.
 */
export declare function streamSessionObserve(handle: ExternalObject<StreamHandle>, sourceType: string, runes: number): number

/**
 * Report arriving `text` on `source_type`, counting Unicode scalars so
 * a host does not have to. Returns the track's new end offset.
 *
 * The engine counts runes, not UTF-16 code units. `Utf16String` yields
 * UTF-16, so the binding decodes to a `String` before delegating to
 * the engine and rune counting stays consistent with every other SDK.
 * An astral-plane character is one rune here even though it is two
 * UTF-16 code units.
 */
export declare function streamSessionObserveText(handle: ExternalObject<StreamHandle>, sourceType: string, text: string): number

/** Runes on `track` observed but not yet released. */
export declare function streamSessionPending(handle: ExternalObject<StreamHandle>, track: string): number

/**
 * Record what `task` decided about the span `[start, end)` of
 * `source_type`. `outcome` is `cleared`, `transformed` or `denied`.
 */
export declare function streamSessionRecordOutcome(handle: ExternalObject<StreamHandle>, task: string, sourceType: string, start: number, end: number, outcome: string): void

/**
 * Record an ACS verdict against the span `[start, end)` of
 * `source_type`, mapping its decision onto an outcome. A host feeds
 * the JSON returned by `policyEvaluate` straight back without
 * translating it.
 */
export declare function streamSessionRecordVerdict(handle: ExternalObject<StreamHandle>, task: string, sourceType: string, start: number, end: number, verdictJson: string): void

/**
 * Offset of `track` the host may release through, or `null` once the
 * session has ended. A settled session has no safe offset, which is
 * not an error: it means release nothing further.
 */
export declare function streamSessionSafeOffset(handle: ExternalObject<StreamHandle>, track: string): number | null

/**
 * Session state as JSON: `is_ended`, `transformed`, `end_reason`
 * (null while live) and the effective `config`.
 */
export declare function streamSessionState(handle: ExternalObject<StreamHandle>): string

/**
 * `track`'s watermark as JSON, carrying `track`, `confirmed`,
 * `received`, `pending` and the `tasks` that must clear it. The
 * confirmed offset stays readable after settlement, so an audit
 * record can still say how far the stream got.
 */
export declare function streamSessionWatermark(handle: ExternalObject<StreamHandle>, track: string): string

/** The manifest grammar versions this engine accepts. */
export declare function supportedManifestVersions(): Array<string>

/**
 * Validate manifest source against the grammar, without building a
 * runtime.
 *
 * Authoring and migration tools need this answer before a policy is
 * runnable, and building a runtime would additionally require the
 * bundled dispatchers and, for Rego, a loadable policy bundle.
 *
 * A rejected manifest comes back as `Some(message)` rather than being
 * thrown, so a thrown error from this function always means the call
 * itself failed and never that the manifest is bad. The wrapper relies
 * on that split so it does not relabel boundary failures as grammar
 * failures.
 */
export declare function validateManifest(source: string): string | null

/**
 * Validate a manifest file, resolving `extends` first.
 *
 * The entry point for a manifest that inherits. Reads from disk and may
 * fetch URL `extends`, exactly as loading a runtime would.
 */
export declare function validateManifestFile(path: string): string | null
