/* auto-generated by NAPI-RS */
/* eslint-disable */

export declare class ExternalObject<T> {
  readonly '': {
    readonly '': unique symbol
    [K: symbol]: T
  }
}
/**
 * Evaluate one agent context (JSON object per AGENT-HOOKS-0.1 §4) and
 * return the verdict as wire JSON.
 */
export declare function intercept(handle: ExternalObject<Handle>, contextJson: string): string

/**
 * Build a runtime handle from a manifest path using the zero-config
 * dispatchers (bundled annotators; Rego through OPA, Cedar through the
 * built-in evaluator, `test` policies through their embedded verdict).
 */
export declare function interceptorNew(manifestPath: string): ExternalObject<Handle>
