// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

namespace AgentControlSpec.ContentSafety;

/// <summary>
/// Role a streaming content safety front door attaches to a payload.
///
/// These mirror the source types such a front door carries on the wire. They
/// are declared here rather than imported so this package builds without a
/// dependency on any particular service's generated contract.
///
/// The numeric values match that wire contract deliberately, so a caller may
/// translate by value as well as by name. Reordering a member here is a
/// breaking change even though nothing in this package reads the numbers.
/// </summary>
public enum ContentSafetySource
{
    /// <summary>No source was set on the payload.</summary>
    Unknown = 0,

    /// <summary>Text authored by the caller.</summary>
    UserRequest = 1,

    /// <summary>Text generated by the model.</summary>
    ModelGenerated = 2,

    /// <summary>The concatenation of every preceding turn.</summary>
    ConcatAll = 3,

    /// <summary>
    /// Context supplied alongside the request, which is not moderated directly
    /// but informs the moderation of adjacent text.
    /// </summary>
    Context = 4,

    /// <summary>Arguments of a tool the agent is about to invoke.</summary>
    PreToolCall = 5,

    /// <summary>Result a tool returned.</summary>
    PostToolCall = 6,

    /// <summary>State captured before an agent run.</summary>
    PreRun = 7,

    /// <summary>State captured after an agent run.</summary>
    PostRun = 8,
}

/// <summary>
/// Scope a task's configuration declares itself applicable to.
///
/// This is a different axis from <see cref="ContentSafetySource"/> and the two
/// MUST NOT be interchanged. A payload carries a
/// <see cref="ContentSafetySource"/> describing what produced its text. A task
/// carries this, describing which part of the exchange it governs. The front
/// door keeps them as separate enumerations and so does this package.
///
/// Only <see cref="Prompt"/>, <see cref="Completion"/> and <see cref="All"/>
/// take part in release gating, because the front door builds exactly two
/// watermarks, one for the prompt and one for the completion, and registers a
/// task on a watermark only when the task's scope equals that watermark's own
/// scope or is <see cref="All"/>. A task scoped to any other value registers on
/// neither watermark and therefore never gates released text.
/// </summary>
public enum ContentSafetyAppliedSource
{
    /// <summary>Governs both the prompt and the completion.</summary>
    All = 0,

    /// <summary>Governs request text.</summary>
    Prompt = 1,

    /// <summary>Governs response text.</summary>
    Completion = 2,

    /// <summary>Governs system instructions. Does not gate released text.</summary>
    System = 3,

    /// <summary>Governs supplied documents. Does not gate released text.</summary>
    Document = 4,

    /// <summary>Governs tool content generally. Does not gate released text.</summary>
    Tool = 5,

    /// <summary>Governs tool call arguments. Does not gate released text.</summary>
    PreToolCall = 6,

    /// <summary>Governs tool results. Does not gate released text.</summary>
    PostToolCall = 7,
}

/// <summary>
/// Payload text kind, used only when <see cref="ContentSafetySource.Unknown"/>
/// leaves the source unset and the kind has to stand in for it.
///
/// The wire contract carries this as a separate, deprecated field whose values
/// are identical to the source type's. Both are modelled here so a caller can
/// translate whichever field its payload populated without remapping.
/// </summary>
public enum ContentSafetyTextKind
{
    Unspecified = 0,
    UserRequest = 1,
    ModelGenerated = 2,
    ConcatAll = 3,
    Context = 4,
    PreToolCall = 5,
    PostToolCall = 6,
    PreRun = 7,
    PostRun = 8,
}

/// <summary>
/// Action a task's configuration asks for when its blocking criterion matches.
/// </summary>
public enum ContentSafetyAction
{
    /// <summary>
    /// No action configured. Treated as <see cref="Block"/>, because an
    /// unconfigured action on a matched criterion MUST NOT weaken enforcement.
    /// </summary>
    Unspecified = 0,

    /// <summary>Record the finding and permit the content.</summary>
    Annotate = 1,

    /// <summary>Refuse the content.</summary>
    Block = 2,

    /// <summary>Route to a human in the loop.</summary>
    Hitl = 3,

    /// <summary>Ask the caller to regenerate.</summary>
    Retry = 4,
}

/// <summary>
/// Accumulator for the actions every task contributed to one segment.
///
/// Several tasks evaluate the same text, so their actions combine rather than
/// replace one another. The combined value collapses to a single action
/// through <see cref="ContentSafetyDecision.Collapse"/>.
/// </summary>
[Flags]
public enum ContentSafetyActionFlags
{
    None = 0,
    Annotate = 1,
    Retry = 2,
    Hitl = 4,
    Block = 8,
}

/// <summary>Bucketed severity used by policies that express a risk level.</summary>
public enum RiskLevel
{
    Unspecified = 0,
    Safe = 1,
    Low = 2,
    Medium = 3,
    High = 4,
}

/// <summary>Shape of the comparison a blocking criterion performs.</summary>
public enum BlockingCriterionKind
{
    Unspecified = 0,

    /// <summary>Compare an integer severity against an allowed severity.</summary>
    Severity = 1,

    /// <summary>Compare a bucketed severity against an allowed risk level.</summary>
    RiskLevel = 2,

    /// <summary>Test a boolean detection flag.</summary>
    IsDetected = 3,

    /// <summary>Compare a floating point score against an allowed score.</summary>
    Score = 4,
}
