// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
// Incremental stream mediation (specification section 18.1).
//
// This is a binding, not an implementation. Every decision about what
// may be released is made by the Rust engine through the C ABI, so a
// host on this SDK and a host on any other answer identically by
// construction rather than by agreement.

using System.Text.Json;
using System.Text.Json.Serialization;

namespace AgentControlSpec;

/// <summary>How much a host withholds while a stream is mediated.</summary>
public enum SafetyLevel
{
    /// <summary>Withhold every rune until a task clears it.</summary>
    Blocking,

    /// <summary>Withhold until the whole payload has been evaluated.</summary>
    Complete,

    /// <summary>Emit on arrival and evaluate behind the stream.</summary>
    Deferred,
}

/// <summary>Which side of the exchange a payload belongs to.</summary>
public enum StreamSourceType
{
    /// <summary>Text authored by the caller.</summary>
    UserRequest,

    /// <summary>Text generated by the model.</summary>
    ModelGenerated,
}

/// <summary>The two independently accounted halves of a stream.</summary>
public enum StreamTrack
{
    /// <summary>Runes flowing toward the model.</summary>
    Request,

    /// <summary>Runes flowing back to the caller.</summary>
    Response,
}

/// <summary>What a task decided about one evaluated span.</summary>
public enum SegmentOutcome
{
    /// <summary>The span may be released unchanged.</summary>
    Cleared,

    /// <summary>The host substitutes its own text. This ends the stream.</summary>
    Transformed,

    /// <summary>The span is refused. This ends the stream.</summary>
    Denied,
}

/// <summary>How far one track got and what still owes a decision.</summary>
/// <param name="Track">The track described.</param>
/// <param name="Confirmed">Runes every task has cleared.</param>
/// <param name="Received">Runes observed.</param>
/// <param name="Pending">Runes observed but not yet released.</param>
/// <param name="Tasks">The tasks that must clear a span before it releases.</param>
public sealed record StreamWatermark(
    [property: JsonPropertyName("track")] string Track,
    [property: JsonPropertyName("confirmed")] int Confirmed,
    [property: JsonPropertyName("received")] int Received,
    [property: JsonPropertyName("pending")] int Pending,
    [property: JsonPropertyName("tasks")] IReadOnlyList<string> Tasks);

/// <summary>Why a session ended.</summary>
/// <param name="Kind">One of <c>complete</c>, <c>denied</c>, <c>rewritten</c> or <c>failed</c>.</param>
/// <param name="Track">The track carrying the span, when a span ended it.</param>
/// <param name="Task">The task that decided, when a task ended it.</param>
/// <param name="Start">Start rune of the deciding span.</param>
/// <param name="End">End rune of the deciding span.</param>
/// <param name="Reason">The engine's reason code, when the session failed.</param>
/// <param name="Message">The engine's message, when the session failed.</param>
public sealed record StreamEndReason(
    [property: JsonPropertyName("kind")] string Kind,
    [property: JsonPropertyName("track")] string? Track = null,
    [property: JsonPropertyName("task")] string? Task = null,
    [property: JsonPropertyName("start")] int? Start = null,
    [property: JsonPropertyName("end")] int? End = null,
    [property: JsonPropertyName("reason")] string? Reason = null,
    [property: JsonPropertyName("message")] string? Message = null);

/// <summary>Terminal settlement of a session.</summary>
/// <param name="Reason">Why the session ended.</param>
/// <param name="Transformed">Whether the emitted text is not verbatim model output.</param>
/// <param name="IsClean">Whether the stream ran to completion without a refusal.</param>
public sealed record StreamCompletion(
    [property: JsonPropertyName("reason")] StreamEndReason Reason,
    [property: JsonPropertyName("transformed")] bool Transformed,
    [property: JsonPropertyName("is_clean")] bool IsClean);

/// <summary>The offsets and task sets a session was opened with.</summary>
/// <param name="SafetyLevel">The withholding level.</param>
/// <param name="RequestStartRuneOffset">Where request accounting begins.</param>
/// <param name="ResponseStartRuneOffset">Where response accounting begins.</param>
/// <param name="RequestTasks">Tasks mediating the request track.</param>
/// <param name="ResponseTasks">Tasks mediating the response track.</param>
public sealed record StreamSessionConfig(
    [property: JsonPropertyName("safety_level")] string SafetyLevel,
    [property: JsonPropertyName("request_start_rune_offset")] int RequestStartRuneOffset,
    [property: JsonPropertyName("response_start_rune_offset")] int ResponseStartRuneOffset,
    [property: JsonPropertyName("request_tasks")] IReadOnlyList<string> RequestTasks,
    [property: JsonPropertyName("response_tasks")] IReadOnlyList<string> ResponseTasks);

/// <summary>Live state of a session.</summary>
/// <param name="IsEnded">Whether the session has settled.</param>
/// <param name="Transformed">Whether a rewrite ended it.</param>
/// <param name="EndReason">Why it ended, or null while it is live.</param>
/// <param name="Config">The configuration in force.</param>
public sealed record StreamSessionState(
    [property: JsonPropertyName("is_ended")] bool IsEnded,
    [property: JsonPropertyName("transformed")] bool Transformed,
    [property: JsonPropertyName("end_reason")] StreamEndReason? EndReason,
    [property: JsonPropertyName("config")] StreamSessionConfig Config);

/// <summary>
/// One mediated stream.
///
/// A host reports arriving payloads, reports what each task decided
/// about each evaluated span, and reads back how far the stream is safe
/// to release. The session holds no text, so applying a rewrite and
/// emitting released runes stay the host's job.
/// </summary>
/// <example>
/// <code>
/// using var session = new StreamSession(
///     SafetyLevel.Blocking, responseTasks: ["pii"]);
/// session.ObserveText(StreamSourceType.ModelGenerated, "hello");
/// session.RecordOutcome("pii", StreamSourceType.ModelGenerated, 0, 5, SegmentOutcome.Cleared);
/// int? release = session.SafeOffset(StreamTrack.Response);
/// </code>
/// </example>
public sealed class StreamSession : IDisposable
{
    private static readonly JsonSerializerOptions Json = new()
    {
        PropertyNameCaseInsensitive = true,
    };

    private readonly StreamSessionHandle _handle;

    /// <summary>Open a session.</summary>
    /// <param name="safetyLevel">How much to withhold while mediating.</param>
    /// <param name="requestTasks">Tasks mediating the request track. Empty leaves it unmediated.</param>
    /// <param name="responseTasks">Tasks mediating the response track. Empty leaves it unmediated.</param>
    /// <param name="requestStartRuneOffset">Where request accounting begins, for a resumed stream.</param>
    /// <param name="responseStartRuneOffset">Where response accounting begins, for a resumed stream.</param>
    /// <exception cref="AgentControlSpecNativeException">
    /// The engine refused the configuration, which includes leaving both
    /// tracks unmediated, because a session that evaluates nothing
    /// releases everything.
    /// </exception>
    public StreamSession(
        SafetyLevel safetyLevel = SafetyLevel.Blocking,
        IEnumerable<string>? requestTasks = null,
        IEnumerable<string>? responseTasks = null,
        int requestStartRuneOffset = 0,
        int responseStartRuneOffset = 0)
    {
        var config = JsonSerializer.Serialize(new Dictionary<string, object>
        {
            ["safety_level"] = Wire(safetyLevel),
            ["request_start_rune_offset"] = requestStartRuneOffset,
            ["response_start_rune_offset"] = responseStartRuneOffset,
            ["request_tasks"] = requestTasks?.ToArray() ?? [],
            ["response_tasks"] = responseTasks?.ToArray() ?? [],
        });
        _handle = Native.StreamSessionNew(config);
    }

    internal static string Wire(SafetyLevel level) => level switch
    {
        AgentControlSpec.SafetyLevel.Blocking => "blocking",
        AgentControlSpec.SafetyLevel.Complete => "complete",
        AgentControlSpec.SafetyLevel.Deferred => "deferred",
        _ => throw new ArgumentOutOfRangeException(nameof(level), level, "unknown safety level"),
    };

    internal static string Wire(StreamSourceType source) => source switch
    {
        StreamSourceType.UserRequest => "user_request",
        StreamSourceType.ModelGenerated => "model_generated",
        _ => throw new ArgumentOutOfRangeException(nameof(source), source, "unknown stream source type"),
    };

    internal static string Wire(StreamTrack track) => track switch
    {
        StreamTrack.Request => "request",
        StreamTrack.Response => "response",
        _ => throw new ArgumentOutOfRangeException(nameof(track), track, "unknown stream track"),
    };

    internal static string Wire(SegmentOutcome outcome) => outcome switch
    {
        SegmentOutcome.Cleared => "cleared",
        SegmentOutcome.Transformed => "transformed",
        SegmentOutcome.Denied => "denied",
        _ => throw new ArgumentOutOfRangeException(nameof(outcome), outcome, "unknown segment outcome"),
    };

    /// <summary>Record that <paramref name="runes"/> more runes arrived.</summary>
    /// <returns>The track's received offset.</returns>
    public int Observe(StreamSourceType sourceType, int runes) =>
        Native.StreamObserve(_handle, Wire(sourceType), checked((uint)runes));

    /// <summary>
    /// Record an arriving payload by its text, counting runes the way the
    /// engine does so a host never counts them itself. A rune is a Unicode
    /// scalar, so an astral-plane character counts once even though it
    /// occupies two UTF-16 code units in a .NET string.
    /// </summary>
    /// <returns>The track's received offset.</returns>
    public int ObserveText(StreamSourceType sourceType, string text) =>
        Native.StreamObserveText(_handle, Wire(sourceType), text);

    /// <summary>Record what <paramref name="task"/> decided about a span.</summary>
    public void RecordOutcome(
        string task, StreamSourceType sourceType, int start, int end, SegmentOutcome outcome) =>
        Native.StreamRecordOutcome(
            _handle, task, Wire(sourceType), checked((uint)start), checked((uint)end), Wire(outcome));

    /// <summary>
    /// Record a verdict against a span, mapping its decision onto an
    /// outcome. Takes a verdict exactly as <see cref="ActivatedPolicy"/>
    /// returns one, so a decision feeds straight back with nothing to
    /// translate.
    /// </summary>
    public void RecordVerdict(
        string task, StreamSourceType sourceType, int start, int end, string verdictJson) =>
        Native.StreamRecordVerdict(
            _handle, task, Wire(sourceType), checked((uint)start), checked((uint)end), verdictJson);

    /// <summary>
    /// Recompute a track's watermark against the outcomes recorded so far.
    /// This is the call that moves the releasable offset; recording an
    /// outcome on its own does not.
    /// </summary>
    /// <returns>The offset it advanced to, or null when it did not advance.</returns>
    public int? Advance(StreamTrack track) => Native.StreamAdvance(_handle, Wire(track));

    /// <summary>
    /// The offset safe to release, as of the last <see cref="Advance"/>.
    /// </summary>
    /// <returns>
    /// The releasable offset, or null once the session has ended. Null
    /// means release nothing further; it is not an error, and a settled
    /// session reports it rather than a stale number that would release
    /// text no task cleared.
    /// </returns>
    public int? SafeOffset(StreamTrack track) => Native.StreamSafeOffset(_handle, Wire(track));

    /// <summary>Runes observed on a track but not yet released.</summary>
    public int Pending(StreamTrack track) => Native.StreamPending(_handle, Wire(track));

    /// <summary>
    /// A track's watermark. The confirmed offset stays readable after
    /// settlement, so an audit record can still say how far the stream got.
    /// </summary>
    public StreamWatermark Watermark(StreamTrack track) =>
        JsonSerializer.Deserialize<StreamWatermark>(Native.StreamWatermark(_handle, Wire(track)), Json)
        ?? throw new AgentControlSpecNativeException("watermark did not deserialize");

    /// <summary>Live session state.</summary>
    public StreamSessionState State =>
        JsonSerializer.Deserialize<StreamSessionState>(Native.StreamState(_handle), Json)
        ?? throw new AgentControlSpecNativeException("state did not deserialize");

    /// <summary>Whether the session has settled.</summary>
    public bool IsEnded => State.IsEnded;

    /// <summary>Whether a rewrite ended the session.</summary>
    public bool Transformed => State.Transformed;

    /// <summary>Why the session ended, or null while it is live.</summary>
    public StreamEndReason? EndReason => State.EndReason;

    /// <summary>The configuration in force.</summary>
    public StreamSessionConfig Config => State.Config;

    /// <summary>Declare that no further payload will arrive.</summary>
    public void EndOfPayloads() => Native.StreamEndOfPayloads(_handle);

    /// <summary>Settle the session. Settling twice returns the same completion.</summary>
    public StreamCompletion Finish() =>
        JsonSerializer.Deserialize<StreamCompletion>(Native.StreamFinish(_handle), Json)
        ?? throw new AgentControlSpecNativeException("completion did not deserialize");

    /// <summary>Release the native session.</summary>
    public void Dispose() => _handle.Dispose();
}
