// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System.Text;

using AgentHooks;

namespace AgentControlSpec;

/// <summary>
/// Release accounting for a host that emits model output before the whole
/// response exists, per specification section 18.1.
///
/// A session holds no policy, performs no evaluation, and stores no stream
/// text. The host already owns the accumulated text, because the host is what
/// receives the payloads, and the host already decides how to cut that text
/// into the units it evaluates. The session tracks how far each task has
/// cleared and reports which prefix the host may emit.
///
/// This leaves the host owing two obligations the session cannot check for
/// it. The text evaluated for a span must cover at least that span, because a
/// policy target smaller than the span it gates lets a banned term slip
/// through a segment boundary. And the rune counts reported must match the
/// text accumulated.
///
/// Offsets are rune offsets counted in Unicode scalar values, matching the
/// Rust core. They are deliberately not <see cref="string.Length"/>, which
/// counts UTF-16 code units and would disagree with the core for any
/// supplementary plane character.
/// </summary>
public enum SafetyLevel
{
    /// <summary>Hold every span until the watermark covers it.</summary>
    Blocking,

    /// <summary>
    /// Hold every span until the watermark covers it. Distinct from
    /// <see cref="Blocking"/> on the wire and identical in release behavior.
    /// </summary>
    Complete,

    /// <summary>
    /// Emit each payload as it arrives and evaluate behind the stream.
    /// Denials still terminate the session, and content already emitted
    /// cannot be recalled.
    /// </summary>
    Deferred,
}

/// <summary>Role that produced a span of stream text.</summary>
public enum StreamSourceType
{
    /// <summary>Text authored by the caller.</summary>
    UserRequest,

    /// <summary>Text generated by the model.</summary>
    ModelGenerated,
}

/// <summary>Independent offset space within a session.</summary>
public enum StreamTrack
{
    Request,
    Response,
}

/// <summary>What a host decided for one span after evaluating it.</summary>
public enum SegmentOutcome
{
    /// <summary>The policy permitted the evaluated text unchanged.</summary>
    Cleared,

    /// <summary>
    /// The policy returned <c>transform</c> and the host will substitute its
    /// own replacement for this span. Applying the replacement is the host's
    /// job, because the session holds no text to apply it to. A rewrite is
    /// terminal, and it is refused once any rune has been released, since
    /// released text can no longer be rewritten.
    /// </summary>
    Transformed,

    /// <summary>
    /// The policy refused the text, or an escalation did not resolve to an
    /// allow.
    /// </summary>
    Denied,
}

/// <summary>Half open rune range.</summary>
public readonly record struct RuneRange(int Start, int End)
{
    public int Length => End > Start ? End - Start : 0;

    public bool IsEmpty => End <= Start;
}

/// <summary>
/// A range of one track that the host evaluated as a unit.
///
/// The host builds this from whatever its segmenter produced. The session
/// never constructs spans from text, because it holds none.
/// </summary>
public readonly record struct StreamSpan(StreamSourceType SourceType, RuneRange Range)
{
    /// <summary>Build a span over the half open rune range [start, end).</summary>
    public static StreamSpan Create(StreamSourceType sourceType, int start, int end)
    {
        if (start < 0)
        {
            throw new StreamMediationException($"span start {start} is negative");
        }

        if (end <= start)
        {
            throw new StreamMediationException("span covers no runes");
        }

        return new StreamSpan(sourceType, new RuneRange(start, end));
    }

    /// <summary>Track this span accumulates on.</summary>
    public StreamTrack Track => SourceType.ToTrack();

    /// <summary>Intervention point that evaluates this span.</summary>
    public InterceptionPoint InterceptionPoint => SourceType.ToInterceptionPoint();
}

/// <summary>Reason a session reached its terminal state.</summary>
public abstract record StreamEndReason
{
    private StreamEndReason()
    {
    }

    /// <summary>Every observed rune was cleared by every task.</summary>
    public sealed record Complete : StreamEndReason;

    /// <summary>A host recorded a denial.</summary>
    public sealed record Denied(StreamTrack Track, string Task, RuneRange Range) : StreamEndReason;

    /// <summary>
    /// A task replaced the policy target, so the stream ended rewritten.
    ///
    /// <para>The replacement is a new whole value. Its runes are not the runes
    /// this session counted, and no task on the track evaluated it, so the
    /// accounting cannot authorize releasing it and reports no watermark for
    /// it. The host evaluates the replacement on the ordinary whole snapshot
    /// path of section 18 and starts a new session to keep streaming.</para>
    /// </summary>
    public sealed record Rewritten(StreamTrack Track, string Task, RuneRange Range) : StreamEndReason;

    /// <summary>The session failed closed.</summary>
    public sealed record Failed(string Detail) : StreamEndReason;

    /// <summary>Whether the stream finished without an enforcement action.</summary>
    public bool IsClean => this is Complete;
}

/// <summary>Terminal settlement of a session.</summary>
/// <param name="Reason">Why the session ended.</param>
/// <param name="Transformed">
/// Whether the session ended in a rewrite, so the text the host emitted is
/// not verbatim model output.
/// </param>
public sealed record StreamCompletion(StreamEndReason Reason, bool Transformed);

/// <summary>
/// A streaming session failed closed. The session is terminal once this is
/// thrown.
/// </summary>
public sealed class StreamMediationException : InvalidOperationException
{
    public StreamMediationException(string message)
        : base(message)
    {
    }

    /// <summary>Reserved reason a host records when this failure denies an action.</summary>
    public string Reason => StreamMediation.FailClosedReason;
}

/// <summary>Streaming parameters a host supplies once, before any payload.</summary>
/// <param name="SafetyLevel">How much the host may release ahead of the watermark.</param>
/// <param name="RequestStartRuneOffset">
/// Offset the first rune of the request track occupies. A retry that resumes a
/// partially delivered stream sets this so offsets stay comparable with the
/// earlier attempt. Held per track because the tracks are independent offset
/// spaces and a retry rarely resumes both. Re sending the prompt while
/// resuming the response is the ordinary case.
/// </param>
/// <param name="ResponseStartRuneOffset">
/// Offset the first rune of the response track occupies, with the same meaning
/// as <paramref name="RequestStartRuneOffset"/>.
/// </param>
/// <param name="RequestTasks">
/// Tasks that gate the request track. Empty means the request track is not
/// mediated, which is the ordinary shape for a host guarding only the model
/// stream. Payload on an unmediated track fails closed.
/// </param>
/// <param name="ResponseTasks">
/// Tasks that gate the response track. Kept separate from
/// <paramref name="RequestTasks"/> because a task bound at one intervention
/// point has no counterpart at the other, and a shared set would stall a
/// track on a task that can never evaluate it.
/// </param>
public sealed record StreamSessionConfig(
    SafetyLevel SafetyLevel,
    int RequestStartRuneOffset,
    int ResponseStartRuneOffset,
    IReadOnlyList<string> RequestTasks,
    IReadOnlyList<string> ResponseTasks)
{

    internal IReadOnlyList<string> TasksFor(StreamTrack track) =>
        track == StreamTrack.Request ? RequestTasks : ResponseTasks;
}

/// <summary>
/// Monotonic minimum offset across a fixed set of tasks.
///
/// Each task reports how far into the track it has cleared. The confirmed
/// offset is the smallest of those, so a prefix is released only when no
/// configured task is still behind it. A task that stalls holds the whole
/// track, which is the intended behavior.
/// </summary>
public sealed class StreamWatermark
{
    private readonly SortedDictionary<string, int> _tasks = new(StringComparer.Ordinal);
    private readonly StreamTrack _track;

    internal StreamWatermark(StreamTrack track, IReadOnlyList<string> tasks, int startOffset)
    {
        if (startOffset < 0)
        {
            throw new StreamMediationException("streaming session start offset is negative");
        }

        foreach (var task in tasks)
        {
            _tasks[task] = startOffset;
        }

        _track = track;
        Confirmed = startOffset;
        Received = startOffset;
    }

    /// <summary>Highest offset released so far.</summary>
    public int Confirmed { get; private set; }

    /// <summary>End offset of the text the session has been told about.</summary>
    public int Received { get; private set; }

    /// <summary>Task labels this watermark tracks, in deterministic order.</summary>
    public IEnumerable<string> Tasks => _tasks.Keys;

    /// <summary>
    /// Runes observed but not yet cleared by every task, as of the last
    /// <see cref="Advance"/>.
    /// </summary>
    public int Pending => Received > Confirmed ? Received - Confirmed : 0;

    internal int Extend(int runes)
    {
        if (runes < 0)
        {
            throw new StreamMediationException("streaming payload reported a negative rune count");
        }

        if (Received > int.MaxValue - runes)
        {
            throw new StreamMediationException("streaming session exceeded the offset ceiling");
        }

        Received += runes;
        return Received;
    }

    /// <summary>
    /// Record that <paramref name="task"/> cleared a span running from
    /// <paramref name="start"/> to <paramref name="offset"/>.
    ///
    /// A stale or repeated offset is ignored rather than treated as an error.
    /// A span that starts past the task's frontier is refused, because
    /// confirming it would release the gap between them, which nothing
    /// evaluated.
    /// </summary>
    internal void Record(string task, int start, int offset)
    {
        if (offset > Received)
        {
            throw new StreamMediationException(
                $"outcome offset {offset} runs past {Received} observed runes");
        }

        if (!_tasks.TryGetValue(task, out var current))
        {
            throw new StreamMediationException(
                $"outcome named task {task} which the {_track.ToWireName()} track does not configure");
        }

        if (offset <= current)
        {
            return;
        }

        if (start > current)
        {
            throw new StreamMediationException(
                $"task {task} cleared through {current} so an outcome starting at {start} would release a gap");
        }

        _tasks[task] = offset;
    }

    /// <summary>
    /// Recompute the confirmed offset. Returns the new offset when it
    /// advanced and <c>null</c> when it did not, so a caller emits a
    /// watermark only on real progress.
    /// </summary>
    public int? Advance()
    {
        var minimum = Confirmed;
        var first = true;
        foreach (var offset in _tasks.Values)
        {
            if (first || offset < minimum)
            {
                minimum = offset;
                first = false;
            }
        }

        if (minimum > Confirmed)
        {
            Confirmed = minimum;
            return Confirmed;
        }

        return null;
    }
}

/// <summary>
/// Release accounting over a stream the host holds.
///
/// The host reports how much text arrived, declares the spans its segmenter
/// produced, evaluates those spans with the ordinary runtime, records each
/// outcome, and asks which prefix it may now release.
///
/// The session settles in two steps. <see cref="EndOfPayloads"/> says no more
/// text is coming while outcomes are still in flight, which is what a
/// <see cref="SafetyLevel.Deferred"/> host needs so a late denial can still
/// land. <see cref="Finish"/> settles the session.
///
/// <para><b>Not thread safe.</b> A caller must serialize every operation on one
/// session. The Rust core this mirrors takes an exclusive reference, so its
/// compiler enforces the same requirement; nothing enforces it here. Advancing
/// the watermark while another thread records an outcome enumerates the task
/// map during mutation and throws. Callers that receive classifier results
/// concurrently should use
/// <c>AgentControlSpec.ContentSafety.ContentSafetySession</c>, which
/// serializes internally.</para>
/// </summary>
public sealed class StreamSession
{
    private readonly StreamWatermark _request;
    private readonly StreamWatermark _response;
    private StreamEndReason? _ended;
    private bool _payloadsClosed;

    public StreamSession(StreamSessionConfig config)
    {
        Config = config ?? throw new ArgumentNullException(nameof(config));
        if (config.RequestTasks.Count == 0 && config.ResponseTasks.Count == 0)
        {
            throw new StreamMediationException(
                "streaming session configured to mediate neither track");
        }

        _request = new StreamWatermark(
            StreamTrack.Request, config.RequestTasks, config.RequestStartRuneOffset);
        _response = new StreamWatermark(
            StreamTrack.Response, config.ResponseTasks, config.ResponseStartRuneOffset);
    }

    /// <summary>Streaming parameters this session was opened with.</summary>
    public StreamSessionConfig Config { get; }

    /// <summary>Terminal reason, when the session has ended.</summary>
    public StreamEndReason? EndReason => _ended;

    /// <summary>Whether the session has reached its terminal state.</summary>
    public bool IsEnded => _ended is not null;

    /// <summary>Whether any span cleared through a transform outcome.</summary>
    /// <summary>
    /// Whether a rewrite ended this session, meaning the host emits a
    /// substitute rather than verbatim model output.
    ///
    /// <para>A rewrite clears nothing, so this says nothing about what was
    /// released. It is exactly <see cref="StreamEndReason.Rewritten"/>,
    /// derived rather than tracked so the two cannot disagree.</para>
    /// </summary>
    public bool Transformed => _ended is StreamEndReason.Rewritten;

    /// <summary>Watermark for a track.</summary>
    public StreamWatermark Watermark(StreamTrack track) =>
        track == StreamTrack.Request ? _request : _response;

    /// <summary>Offset through which the host may emit this track.</summary>
    /// <summary>
    /// Offset through which the host may emit this track, or <c>null</c> once
    /// the session has ended.
    ///
    /// <para>A deny withholds every rune the host has not already emitted,
    /// including runes a task had cleared, so a terminal session has no offset
    /// anyone may emit through. The offset the track reached stays readable
    /// through <see cref="Watermark"/> for an audit record.</para>
    /// </summary>
    public int? SafeOffset(StreamTrack track) =>
        _ended is not null ? null : Watermark(track).Confirmed;

    /// <summary>Runes observed but not yet cleared by every task on this track.</summary>
    public int Pending(StreamTrack track) => Watermark(track).Pending;

    /// <summary>
    /// Report that <paramref name="runes"/> more runes arrived on this role's
    /// track, and return the track's new end offset.
    ///
    /// This only moves the bound that outcomes are checked against. It does
    /// not release anything and does not decide what the host evaluates.
    /// </summary>
    public int Observe(StreamSourceType sourceType, int runes)
    {
        EnsureOpen();
        if (_payloadsClosed)
        {
            // Terminal rather than merely refused. Text arriving after the
            // host declared EOF means the session was told the stream ended
            // when it had not, and a host that ignored the refusal would
            // settle clean over runes the accounting never counted.
            Fail("streaming payload stream already closed");
        }

        var track = sourceType.ToTrack();
        if (Config.TasksFor(track).Count == 0)
        {
            // An unmediated track gates nothing, so it takes nothing.
            Fail($"payload arrived on the unmediated {track} track");
        }

        return Guard(() => Watermark(track).Extend(runes));
    }

    /// <summary>
    /// Report arriving text by counting its runes.
    ///
    /// Provided so a host does not reach for <see cref="string.Length"/>,
    /// which counts UTF-16 code units and is not interchangeable with a rune
    /// offset. The text itself is not retained.
    /// </summary>
    public int ObserveText(StreamSourceType sourceType, string text)
    {
        ArgumentNullException.ThrowIfNull(text);
        return Observe(sourceType, CountRunes(text));
    }

    /// <summary>Count Unicode scalar values, not UTF-16 code units.</summary>
    public static int CountRunes(string text)
    {
        ArgumentNullException.ThrowIfNull(text);
        var runes = 0;
        foreach (var _ in text.EnumerateRunes())
        {
            runes++;
        }

        return runes;
    }

    /// <summary>Record what a host decided for <paramref name="span"/> under <paramref name="task"/>.</summary>
    public void RecordOutcome(string task, StreamSpan span, SegmentOutcome outcome)
    {
        ArgumentNullException.ThrowIfNull(task);
        EnsureOpen();

        var track = span.Track;
        if (!Config.TasksFor(track).Contains(task, StringComparer.Ordinal))
        {
            Fail($"outcome named task {task} which the {track.ToWireName()} track does not configure");
        }

        if (span.Range.IsEmpty)
        {
            Fail("span covers no runes");
        }

        // Validated for every outcome, including a refusal. A span past the
        // observed end means the host and the session disagree about how much
        // text exists, and recording a refusal over runes the session was never
        // told about would carry that disagreement into the terminal reason and
        // into whatever audits it.
        var received = Watermark(track).Received;
        if (span.Range.End > received)
        {
            Fail($"outcome offset {span.Range.End} runs past {received} observed runes");
        }

        switch (outcome)
        {
            case SegmentOutcome.Denied:
                _ended = new StreamEndReason.Denied(track, task, span.Range);
                return;

            case SegmentOutcome.Transformed:
                // A transform is only meaningful while the host can still
                // alter the text it rewrites. Under a non withholding level
                // the payload was emitted on arrival, so nothing can be
                // rewritten.
                if (!Config.SafetyLevel.Withholds())
                {
                    Fail("transform outcome named text the host has already emitted");
                }

                // The bound is any released rune rather than the span start. A
                // transform names a node of the policy target and not a rune
                // range, and this type holds no text, so it cannot know how far
                // below the span the target reaches. A host evaluating the
                // accumulated prefix has a target covering the whole track.
                if (Watermark(track).Confirmed > 0)
                {
                    Fail("transform outcome named text the host has already emitted");
                }

                // A rewrite ends the session. The substitution replaces the
                // policy target with a new whole value whose runes are not the
                // ones this session counted and which no task evaluated, so no
                // watermark over it means anything.
                _ended = new StreamEndReason.Rewritten(track, task, span.Range);
                return;

            case SegmentOutcome.Cleared:
                break;

            default:
                Fail($"unknown streaming segment outcome {outcome}");
                break;
        }

        Guard(() =>
        {
            Watermark(track).Record(task, span.Range.Start, span.Range.End);
            return 0;
        });
    }

    /// <summary>
    /// Map an ACS verdict onto an outcome and record it.
    ///
    /// <c>allow</c> clears and <c>deny</c> denies. <c>transform</c> records a
    /// rewrite, which obliges the host to apply the verdict's replacement to
    /// this span and ends the session. Any other decision is refused rather
    /// than mapped, because treating an unrecognised decision as a clear would
    /// release text no policy passed.
    /// </summary>
    public void RecordVerdict(string task, StreamSpan span, Verdict verdict)
    {
        ArgumentNullException.ThrowIfNull(verdict);
        var outcome = verdict.Decision switch
        {
            Decision.Allow => SegmentOutcome.Cleared,
            Decision.Deny => SegmentOutcome.Denied,
            Decision.Transform => SegmentOutcome.Transformed,
            _ => throw new StreamMediationException(
                $"unknown Agent Control Specification decision {verdict.Decision}"),
        };
        RecordOutcome(task, span, outcome);
    }

    /// <summary>
    /// Recompute the watermark for <paramref name="track"/> and return it when
    /// it advanced.
    /// </summary>
    public int? Advance(StreamTrack track) => _ended is not null ? null : Watermark(track).Advance();

    /// <summary>
    /// Stop accepting payloads while outcomes are still in flight.
    ///
    /// A <see cref="SafetyLevel.Deferred"/> host calls this at payload EOF so
    /// a classifier running behind the stream can still record a denial before
    /// <see cref="Finish"/>.
    /// </summary>
    public void EndOfPayloads() => _payloadsClosed = true;

    /// <summary>
    /// Settle the session.
    ///
    /// Recomputes both watermarks first, so a host that recorded every outcome
    /// is not failed closed for having skipped an explicit
    /// <see cref="Advance"/>. Any rune no task cleared is a fail closed
    /// condition under every safety level: a deferred host cannot recall what
    /// it emitted, but it can still refuse to settle the stream clean.
    /// </summary>
    public StreamCompletion Finish()
    {
        if (_ended is not null)
        {
            return new StreamCompletion(_ended, Transformed);
        }

        _payloadsClosed = true;
        _request.Advance();
        _response.Advance();

        foreach (var track in new[] { StreamTrack.Request, StreamTrack.Response })
        {
            var pending = Watermark(track).Pending;
            if (pending > 0)
            {
                var reason = new StreamEndReason.Failed(
                    $"{track.ToWireName()} track ended with {pending} uncleared runes");
                _ended = reason;
                return new StreamCompletion(reason, Transformed);
            }
        }

        _ended = new StreamEndReason.Complete();
        return new StreamCompletion(_ended, Transformed);
    }

    private void EnsureOpen()
    {
        if (_ended is not null)
        {
            throw new StreamMediationException("streaming session already closed");
        }
    }

    /// <summary>
    /// Run an accounting step, recording the first terminal reason so a
    /// recorded denial is never downgraded to a transport failure.
    /// </summary>
    private int Guard(Func<int> step)
    {
        try
        {
            return step();
        }
        catch (StreamMediationException error)
        {
            _ended ??= new StreamEndReason.Failed(error.Message);
            throw;
        }
    }

    private void Fail(string detail)
    {
        _ended ??= new StreamEndReason.Failed(detail);
        throw new StreamMediationException(detail);
    }
}

/// <summary>Wire names and reserved values for the streaming contract.</summary>
public static class StreamMediation
{
    /// <summary>Reserved reason recorded when a streaming session fails closed.</summary>
    public const string FailClosedReason = "runtime_error:streaming_unsupported";

    /// <summary>Largest rune offset a session may reach.</summary>
    public const int MaxRuneOffset = int.MaxValue;
}

public static class StreamMediationExtensions
{
    public static string ToWireName(this SafetyLevel level) => level switch
    {
        SafetyLevel.Blocking => "blocking",
        SafetyLevel.Complete => "complete",
        SafetyLevel.Deferred => "deferred",
        _ => throw new ArgumentOutOfRangeException(nameof(level), level, "Unknown streaming safety level."),
    };

    public static SafetyLevel ParseSafetyLevel(string value) => value switch
    {
        "blocking" => SafetyLevel.Blocking,
        "complete" => SafetyLevel.Complete,
        "deferred" => SafetyLevel.Deferred,
        _ => throw new StreamMediationException($"unknown streaming safety level {value}"),
    };

    /// <summary>Whether a host must wait for the watermark before emitting a span.</summary>
    public static bool Withholds(this SafetyLevel level) =>
        level is SafetyLevel.Blocking or SafetyLevel.Complete;

    public static string ToWireName(this StreamSourceType sourceType) => sourceType switch
    {
        StreamSourceType.UserRequest => "user_request",
        StreamSourceType.ModelGenerated => "model_generated",
        _ => throw new ArgumentOutOfRangeException(nameof(sourceType), sourceType, "Unknown stream source type."),
    };

    public static StreamSourceType ParseSourceType(string value) => value switch
    {
        "user_request" => StreamSourceType.UserRequest,
        "model_generated" => StreamSourceType.ModelGenerated,
        _ => throw new StreamMediationException($"unknown stream source type {value}"),
    };

    public static string ToWireName(this StreamTrack track) => track switch
    {
        StreamTrack.Request => "request",
        StreamTrack.Response => "response",
        _ => throw new ArgumentOutOfRangeException(nameof(track), track, "Unknown stream track."),
    };

    public static InterceptionPoint ToInterceptionPoint(this StreamSourceType sourceType) => sourceType switch
    {
        StreamSourceType.UserRequest => InterceptionPoint.Input,
        StreamSourceType.ModelGenerated => InterceptionPoint.PostModelCall,
        _ => throw new ArgumentOutOfRangeException(nameof(sourceType), sourceType, "Unknown stream source type."),
    };

    public static StreamTrack ToTrack(this StreamSourceType sourceType) => sourceType switch
    {
        StreamSourceType.UserRequest => StreamTrack.Request,
        StreamSourceType.ModelGenerated => StreamTrack.Response,
        _ => throw new ArgumentOutOfRangeException(nameof(sourceType), sourceType, "Unknown stream source type."),
    };
}
